export const navOpts = ['hub', 'tools', 'my account', 'dashboard', 'help'];

export const tasks = [
  {
    title: 'Complete Introduction to JavaScript Course',
    desc: 'This course covers the fundamentals of JavaScript programming, including variables, functions, control flow, and more.',
    status: 'pending',
    dueDate: '05-12-2023',
    id: '1',
  },
  {
    title: 'Write Research Paper on Climate Change',
    desc: 'The research paper will analyze the impacts of climate change on ecosystems, human societies, and global economies.',
    status: 'due',
    dueDate: '15-03-2024',
    id: '2',
  },
  {
    title: 'Prepare Presentation for Team Meeting',
    desc: 'The presentation will highlight key project milestones, challenges, and proposed solutions for the upcoming quarter.',
    status: 'completed',
    dueDate: '28-01-2024',
    id: '3',
  },
  {
    title: 'Review Quarterly Financial Reports',
    desc: 'Analyze financial statements, balance sheets, and income statements to assess company performance and identify trends.',
    status: 'completed',
    dueDate: '15-02-2024',
    id: '4',
  },
  {
    title: 'Design User Interface for Mobile App',
    desc: 'Create wireframes, mockups, and prototypes for the user interface of a new mobile application.',
    status: 'pending',
    dueDate: '10-03-2024',
    id: '5',
  },
  {
    title: 'Update Company Website Content',
    desc: 'Revise website copy, update product descriptions, and optimize content for search engine visibility.',
    status: 'completed',
    dueDate: '20-04-2024',
    id: '6',
  },
  {
    title: 'Organize Charity Event Fundraiser',
    desc: 'Coordinate logistics, secure sponsors, and promote the charity event to raise funds for a local cause.',
    status: 'due',
    dueDate: '30-05-2024',
    id: '7',
  },
  {
    title: 'Attend Professional Development Seminar',
    desc: 'Participate in workshops, panels, and networking events to enhance professional skills and knowledge.',
    status: 'pending',
    dueDate: '10-06-2024',
    id: '8',
  },
  {
    title: 'Write Blog Post on Industry Trends',
    desc: 'Research emerging trends and developments in the industry and share insights with the target audience.',
    status: 'due',
    dueDate: '05-07-2024',
    id: '9',
  },
  {
    title: 'Create Marketing Campaign for New Product Launch',
    desc: 'Develop creative concepts, design marketing materials, and execute digital and traditional advertising campaigns.',
    status: 'pending',
    dueDate: '20-08-2024',
    id: '10',
  },
  {
    title: 'Conduct Customer Satisfaction Survey',
    desc: 'Gather feedback from customers to evaluate satisfaction levels, identify areas for improvement, and measure loyalty.',
    status: 'completed',
    dueDate: '15-09-2024',
    id: '11',
  },
  {
    title: 'Revise Employee Handbook Policies',
    desc: 'Update company policies, procedures, and guidelines to ensure compliance with current regulations and best practices.',
    status: 'completed',
    dueDate: '10-10-2024',
    id: '12',
  },
  {
    title: 'Plan Team Building Retreat',
    desc: 'Organize team building activities, workshops, and exercises to foster collaboration and morale among team members.',
    status: 'pending',
    dueDate: '25-11-2024',
    id: '13',
  },
  {
    title: 'Research Market Trends and Competitor Analysis',
    desc: 'Analyze market data, consumer behavior, and competitor strategies to inform business decision-making.',
    status: 'due',
    dueDate: '05-12-2024',
    id: '14',
  },
  {
    title: 'Create Training Program for New Employees',
    desc: 'Develop training materials, modules, and presentations to onboard new hires and facilitate their integration into the company.',
    status: 'pending',
    dueDate: '15-01-2025',
    id: '15',
  },
  {
    title: 'Implement Customer Relationship Management System',
    desc: 'Select, configure, and deploy a CRM system to manage customer interactions, sales pipelines, and marketing campaigns.',
    status: 'completed',
    dueDate: '10-02-2025',
    id: '16',
  },
  {
    title: 'Coordinate Product Launch Event',
    desc: 'Plan event logistics, coordinate vendors, and execute promotional activities to launch a new product successfully.',
    status: 'completed',
    dueDate: '20-03-2025',
    id: '17',
  },
  {
    title: 'Optimize Supply Chain Logistics',
    desc: 'Streamline inventory management, optimize transportation routes, and reduce costs in the supply chain network.',
    status: 'pending',
    dueDate: '05-04-2025',
    id: '18',
  },
  {
    title: 'Prepare Annual Budget Forecast',
    desc: 'Analyze financial data, market trends, and business forecasts to develop an accurate budget projection for the upcoming year.',
    status: 'due',
    dueDate: '15-05-2025',
    id: '19',
  },
  {
    title: 'Conduct Employee Performance Reviews',
    desc: 'Evaluate employee performance, provide feedback, and set goals and objectives for professional development.',
    status: 'pending',
    dueDate: '10-06-2025',
    id: '20',
  },
  {
    title: 'Create Social Media Content Calendar',
    desc: 'Plan and schedule social media posts, campaigns, and promotions to engage and grow the online audience.',
    status: 'due',
    dueDate: '20-07-2025',
    id: '21',
  },
  {
    title: 'Develop Mobile App Prototype',
    desc: 'Design user interface wireframes, create interactive prototypes, and conduct usability testing for a mobile application.',
    status: 'completed',
    dueDate: '05-08-2025',
    id: '22',
  },
  {
    title: 'Organize Company Volunteer Day',
    desc: 'Coordinate volunteer activities, select community service projects, and engage employees in giving back to the community.',
    status: 'pending',
    dueDate: '10-09-2025',
    id: '23',
  },
  {
    title: 'Review Quarterly Sales Performance',
    desc: 'Analyze sales data, assess performance metrics, and identify opportunities for growth and improvement.',
    status: 'completed',
    dueDate: '25-10-2025',
    id: '24',
  },
  {
    title: 'Plan Corporate Retreat for Executive Team',
    desc: 'Organize strategic planning sessions, team building exercises, and leadership development workshops for executive leaders.',
    status: 'completed',
    dueDate: '15-11-2025',
    id: '25',
  },
  {
    title: 'Research and Implement Green Initiatives',
    desc: 'Explore sustainability practices, evaluate environmental impact, and implement eco-friendly initiatives across company operations.',
    status: 'pending',
    dueDate: '20-12-2025',
    id: '26',
  },
];
